import { Poppins } from 'next/font/google';
import Header from './components/Header';
import './globals.scss?4444444';

const fontFace = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  style: ['italic', 'normal']
});

export const metadata = {
  title: 'Movies (Next.js)',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${fontFace.className}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
