import { Poppins } from 'next/font/google';
import Search from './components/Search';
import './globals.scss?333333333333333333333333333333333333333333';

const fontFace = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  style: ['italic', 'normal']
});

export const metadata = {
  title: "Movies (Next.js)",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${fontFace.className}`}>
        <Search />
        {children}
      </body>
    </html>
  );
}
