import { Poppins } from 'next/font/google';
import Search from './components/Search';
import Navigation from './components/Navigation';
import { fetch_options, tmdb_base, setGenres } from '@/app/api';
import './globals.scss?4444444444444';

const fontFace = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  style: ['italic', 'normal']
});

export const metadata = {
  title: 'Movies (Next.js)',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const data = await fetch(tmdb_base + '/genre/movie/list?language=en', fetch_options);
  const genres = await data.json();
  setGenres(genres.genres);
  return (
    <html lang="en">
      <body className={`${fontFace.className}`}>
        <Search />
        <Navigation />
        {children}
      </body>
    </html>
  );
}
