const roles = [
  'Director',
  'Writer',
  'Screenplay',
  'Original Film Writer',
  'Story',
  'Novel',
  'Graphic Novel',
  'Editor',
  'Online Editor',
  'Assistant Editor',
  'Director of Photography',
  'Colorist',
  'Digital Colorist',
  'Digital Intermediate Colorist',
  'Production Assistant',
  'First Assistant Director',
  'Second Assistant Director',
  'Second Second Assistant Director',
  'Third Assistant Director',
  'Assistant Director',
  'Additional Second Assistant Director',
  'Head of Production',
  'Executive Producer',
  'Co-Executive Producer',
  'Executive Producer\'s Assistant',
  'Production Supervisor',
  'Producer',
  'Producer\'s Assistant',
  'Line Producer',
  'Casting',
  'Casting Associate',
  'Casting Assistant',
  'Location Casting',
  'Local Casting',
  'Extras Casting',
  'Extras Casting Coordinator',
  'Extras Casting Assistant',
  'Creative Director',
  'Production Design',
  'Set Decoration',
  'Assistant Set Decoration',
  'Prop Maker',
  'Dolly Grip',
  'Aerial Director of Photography',
  'Set Dresser',
  'On Set Dresser',
  'Set Designer',
  'Key Set Costumer',
  'Set Costumer',
  'Art Direction',
  'Production Sound Mixer',
  'Sound Mixer',
  'Steadicam Operator',
  'Script Supervisor',
  'Additional Script Supervisor',
  'Script Coordinator',
  'Script Editor',
  'Key Costumer',
  'Researcher',
  'Fight Choreographer',
  'Special Effects Technician',
  'Special Effects Coordinator',
  'Special Effects Supervisor',
  'Special Effects',
  'Animation Supervisor',
  'Compositors',
  'CG Supervisor',
  'Actor\'s Assistant',
  'Boom Operator',
  'Stunt Coordinator',
  'Hair Supervisor',
  'Digital Intermediate Producer',
  'Video Assist Operator',
  'Digital Intermediate Editor',
  'Associate Editor',
  'Sound',
  'Sound Supervisor',
  'Sound Re-Recording Assistant',
  'VFX Supervisor',
  'VFX Production Coordinator',
  'VFX Artist',
  'VFX Editor',
  'Visual Effects Compositor',
  'Matte Painter',
  'Compositing Supervisor',
  'Compositing Lead',
  'Compositing Artist',
  'Negative Cutter',
  'I/O Manager',
  '3D Coordinator',
  'Data Wrangler',
  'Costume Supervisor',
  'Hairstylist',
  'Still Photographer',
  'Makeup Designer',
  'Songs',
  'CG Artist',
  'Assistant Makeup Artist',
  'Draughtsman',
  'Costume Design',
  'Principal Costumer',
  'Prosthetic Makeup Artist',
  'Visual Effects Supervisor',
  'Visual Effects Producer',
  'Visual Effects Coordinator',
  'Visual Effects Editor',
  'Visual Effects',
  'Key Grip',
  'Grip',
  'Gaffer',
  'Principal Costumer',
  'Production Manager',
  'Unit Production Manager',
  'Makeup Supervisor',
  'Key Makeup Artist',
  'Makeup Artist',
  'Set Buyer',
  'Makeup Effects Designer',
  'Modeling',
  'Special Effects Makeup Artist',
  'Post Production Producer',
  'Pyrotechnician',
  'Additional Production Sound Mixer',
  'Production Intern',
  'Underwater Camera',
  'Mix Technician',
  'Visual Development',
  'Libra Head Technician',
  'Assistant Art Director',
  'Stunts',
  'Stunt Driver',
  'Co-Producer',
  'Property Master',
  'Assistant Property Master',
  'Second Unit Director',
  'Sound Designer',
  'Foley Supervisor',
  'Foley Artist',
  'Foley Editor',
  'Foley Mixer',
  'Foley Recordist',
  'Sound Designer',
  'Foley',
  'Supervising Sound Editor',
  'Sound Editor',
  'Sound Re-Recording Mixer',
  'Choreographer',
  'Hair Designer',
  'Truck Costumer',
  'Color Assistant',
  'Title Designer',
  '"A" Camera Operator',
  '"B" Camera Operator',
  'First Assistant "A" Camera',
  'Second Assistant "A" Camera',
  'First Assistant "B" Camera',
  'Second Assistant "B" Camera',
  'Second Unit Director of Photography',
  'Original Music Composer',
  'Art Department Coordinator',
  'Graphic Designer',
  'Prosthetics',
  'First Assistant Sound Editor',
  'Assistant Sound Editor',
  'Sound Effects Editor',
  'Sound Effects Designer',
  'Scoring Mixer',
  'Additional Editing',
  'Set Decorating Coordinator',
  'Book',
  'Associate Producer',
  'Makeup Department Head',
  'Hair Department Head',
  'Prosthetic Supervisor',
  'Scenic Artist',
  'Leadman',
  'Greensman',
  'Supervising ADR Editor',
  'ADR Supervisor',
  'ADR & Dubbing',
  'ADR Editor',
  'ADR Mixer',
  'ADR Recordist',
  'ADR Voice Casting',
  'Construction Coordinator',
  'Wigmaker',
  'Post Production Supervisor',
  'Supervising Art Director',
  'Utility Stunts',
  'Second Unit First Assistant Director',
  'Conceptual Illustrator',
  'Driver',
  'Costume Designer',
  'Standby Art Director',
  'Digital Imaging Technician',
  'Wardrobe Master',
  'Additional Sound Re-Recording Mixer',
  'Costume Coordinator',
  'Assistant Costume Designer',
  'Digital Intermediate',
  'Music Supervisor',
  'Music Editor',
  'Music Coordinator',
  'Music',
  'Dailies Technician',
  'Dailies Manager',
  'Dailies Operator',
  'Clapper Loader',
  'Transportation Captain',
  'Transportation Co-Captain',
  'Transportation Coordinator',
  'Supervising Dialogue Editor',
  'Production Accountant',
  'First Assistant Accountant',
  'Post Production Accountant',
  'Post Coordinator',
  'Digital Effects Supervisor',
  'Best Boy Grip',
  'In Memory Of',
  '3D Supervisor',
  'Key Hair Stylist',
  'Chief Lighting Technician',
  'Animal Coordinator',
  'Production Runner',
  'Dialogue Editor',
  'Utility Sound',
  'Stunt Double',
  'Dialect Coach',
  'Dialogue Coach',
  'Location Manager',
  'Camera Operator',
  'Rigging Grip',
  'Rigging Gaffer',
  'First Assistant Camera',
  'Assistant Camera',
  'Electrician',
  'Lighting Technician',
  'Executive Music Producer',
  'Set Production Assistant',
  'Set Medic',
  'Unit Publicist',
  'Visual Effects Production Assistant',
  'Main Title Designer',
  'Sculptor',
  'Color Timer',
  'Storyboard Artist',
  'First Assistant Editor',
  'Assistant Sound Engineer',
  'Second Assistant Camera',
  'Pilot',
  'Production Coordinator',
  'Compositor',
  'Aerial Coordinator',
  'Sound Recordist',
  'Supervising Armorer',
  'Armorer',
  'Production Secretary',
  'Supervising Music Editor',
  'First Assistant Makeup Artist',
  'Ager/Dyer',
  'Standby Painter',
  'Costume Standby',
  'Costume Assistant',
  'Author',
  'First Assistant Art Direction',
  'Sound Mix Technician',
  'Textile Artist',
  'Wardrobe Assistant',
  'Hair Assistant',
  'Costumer',
  'Construction Foreman',
  'Concept Artist',
  'Orchestrator',
  'Hairdresser',
  'Prosthetic Designer',
  'Underwater Director of Photography',
  'Props',
  'Location Sound Mixer',
  'Consulting Editor',
  'Dressing Prop',
  'Art Department Assistant',
  'Focus Puller',
  'Carpenter',
  'Construction Manager',
  'Marine Coordinator',
  'Assistant Production Manager',
  'Unit Manager',
  'Sound Assistant',
  'Special Effects Manager',
  'Drone Pilot',
  'Drone Operator',
  'First Assistant "C" Camera',
  'Assistant Production Coordinator',
  'First Company Grip',
  'Executive Visual Effects Producer',
  'Digital Effects Producer',
  'Makeup Effects',
  'Visual Effects Camera',
  'Dolby Consultant',
  'Best Boy Electric',
  'Key Rigging Grip',
  'Generator Operator',
  'Tailor',
  'Set Decoration Buyer',
  'Assistant Chief Lighting Technician',
  'Makeup & Hair',
  'Visual Effects Designer',
  'Loader',
  'Additional Editor',
  'Post Production Coordinator',
  'Digital Compositor',
  'Location Coordinator',
  'Additional Production Assistant',
  'Editorial Production Assistant',
  'Second Assistant Accountant',
  'Assistant Location Manager',
  'Studio Teacher',
  'Production Controller',
  'Production Driver',
  'Additional Grip',
  'Additional First Assistant Camera',
  'Additional Second Assistant Camera',
  'Key Set Production Assistant',
  'Lighting Programmer',
  'Visual Effects Production Manager',
  'Location Assistant',
  'Lighting Artist',
  'Additional Music',
  'Executive In Charge Of Production',
  'Contact Lens Technician',
  'Painter',
  'Music Consultant',
  'Additional Camera',
  'Motion Capture Artist',
  'Conceptual Design',
  'Legal Services',
  'Animation',
  'Animation Director',
  'Visual Effects Art Director',
  'Senior Modeller',
  'Craft Service',
  'Payroll Accountant',
  'Camera Production Assistant',
  '24 Frame Playback',
  'Editorial Staff',
  'Set Dressing Artist',
  'Finance',
  'Production Office Assistant',
  'Techno Crane Operator',
  'Aerial Camera',
  'Aerial Camera Technician',
  'BTS Photographer',
  'Camera Loader',
  'Epk Camera Operator',
  'Second Assistant "C" Camera',
  'Russian Arm Operator',
  'Digital Intermediate Assistant',
  'Publicist',
  'Travel Coordinator',
  'Comic Book',
  'Lyricist',
  'Theatre Play',
  'Second Assistant Sound',
  'Senior Visual Effects Supervisor',
  'Post Producer',
  'Senior Animator',
  'Generalist',
  'Matchmove Supervisor',
  'Security',
  'Location Scout',
  'Picture Car Coordinator',
  'Stand In',
  'Other',
  'Thanks',
];

export default roles;