const roles = [
  'Director',
  'Co-Director',
  'Writer',
  'Co-Writer',
  'Screenplay',
  'Screenstory',
  'Original Film Writer',
  'Story',
  'Novel',
  'Graphic Novel',
  'Graphic Novel Illustrator',
  'Editor',
  'Online Editor',
  'Assistant Editor',
  'Director of Photography',
  'Cinematography',
  'Senior Colorist',
  'Colorist',
  'Color Grading',
  'Digital Colorist',
  'Additional Colorist',
  'Digital Intermediate Colorist',
  'Telecine Colorist',
  'First Assistant Director',
  'Second Assistant Director',
  'Second Second Assistant Director',
  'Third Assistant Director',
  'Assistant Director',
  'Additional Second Assistant Director',
  'Production Assistant',
  'Assistant Production Coordinator',
  'First Assistant Production Coordinator',
  'Second Assistant Production Coordinator',
  'Production Coordinator',
  'Trainee Production Coordinator',
  'Head of Production',
  'Executive Producer',
  'Co-Executive Producer',
  'Executive Producer\'s Assistant',
  'Production Supervisor',
  'Producer',
  'Co-Producer',
  'Producer\'s Assistant',
  'Line Producer',
  'Casting Director',
  'Casting Coordinator',
  'Casting Assistant',
  'Casting Associate',
  'Casting',
  'Casting Consultant',
  'Additional Casting',
  'Location Casting',
  'Local Casting',
  'Extras Casting',
  'Extras Casting Coordinator',
  'Extras Casting Assistant',
  'Creative Director',
  'Production Design',
  'Set Decoration',
  'Assistant Set Decoration',
  'Prop Maker',
  'Dolly Grip',
  'Aerial Director of Photography',
  'Set Dresser',
  'Assistant Set Dresser',
  'On Set Dresser',
  'Set Designer',
  'Key Set Costumer',
  'Set Costumer',
  'Art Direction',
  'Crowd Assistant Director',
  'Production Sound Mixer',
  'Sound Mixer',
  'Sound mixer',
  'Steadicam Operator',
  'Script Supervisor',
  'Additional Script Supervisor',
  'Script Coordinator',
  'Script Editor',
  'Key Costumer',
  'Researcher',
  'Choreographer',
  'Associate Choreographer',
  'Fight Choreographer',
  'Martial Arts Choreographer',
  'Special Effects Technician',
  'Special Effects Coordinator',
  'Special Effects Supervisor',
  'Special Effects',
  'Animation Supervisor',
  'Compositors',
  'CG Supervisor',
  'Actor\'s Assistant',
  'Boom Operator',
  'Stunt Coordinator',
  'Digital Intermediate Producer',
  'Video Assist Operator',
  'Digital Intermediate Editor',
  'Associate Editor',
  'Sound',
  'Sound Supervisor',
  'Sound Re-Recording Assistant',
  'VFX Supervisor',
  'VFX Production Coordinator',
  'VFX Artist',
  'VFX Editor',
  'Visual Effects Compositor',
  'Matte Painter',
  'Compositing Supervisor',
  'Compositing Lead',
  'Compositing Artist',
  'Negative Cutter',
  'I/O Manager',
  '3D Coordinator',
  'Data Wrangler',
  'Costume Supervisor',
  'Still Photographer',
  'Makeup Designer',
  'Songs',
  'CG Artist',
  'Assistant Makeup Artist',
  'Draughtsman',
  'Costume Design',
  'Principal Costumer',
  'Makeup Trainee',
  'Visual Effects Supervisor',
  'Visual Effects Producer',
  'Visual Effects Coordinator',
  'Visual Effects Editor',
  'Visual Effects',
  'Key Grip',
  'Grip',
  'Assistant Grip',
  'Gaffer',
  'Principal Costumer',
  'Production Manager',
  'Unit Production Manager',
  'Makeup Supervisor',
  'Key Makeup Artist',
  'Makeup Artist',
  'Makeup Effects Designer',
  'Modeling',
  'Special Effects Makeup Artist',
  'Post Production Producer',
  'Pyrotechnician',
  'Additional Production Sound Mixer',
  'Production Intern',
  'Mix Technician',
  'Visual Development',
  'Libra Head Technician',
  'Stunts',
  'Stunt Driver',
  'Set Buyer',
  'Set Dressing Buyer',
  'Set Decoration Buyer',
  'Assistant Set Decoration Buyer',
  'Construction Buyer',
  'Property Buyer',
  'Property Master',
  'Assistant Property Master',
  'Standby Property Master',
  'Camera Trainee',
  'Rigging Supervisor',
  'Data Management Technician',
  'Seamstress',
  'Assistant Script',
  'Cast Driver',
  'Head Carpenter',
  'Key Carpenter',
  'Carpenter',
  'Standby Carpenter',
  'Supervising Carpenter',
  'Key Production Assistant',
  'Production Consultant',
  'Catering',
  'Production Executive',
  'Second Unit Director',
  'Sound Designer',
  'Foley Supervisor',
  'Foley Artist',
  'Assistant Foley Artist',
  'Foley Editor',
  'Foley Mixer',
  'Foley Recordist',
  'Foley Recording Engineer',
  'Foley',
  'Sound Designer',
  'Supervising Sound Editor',
  'Sound Editor',
  'Sound Re-Recording Mixer',
  'Hair Department Head',
  'Hair Supervisor',
  'Hair Designer',
  'Hair Setup',
  'Key Hair Stylist',
  'Hair Stylist',
  'Hairstylist',
  'First Assistant Hairstylist',
  'Assistant Hairstylist',
  'Additional Hairstylist',
  'Key Hairdresser',
  'Hairdresser',
  'Hair Assistant',
  'Makeup & Hair',
  'Vocal Coach',
  'Master Lighting Artist',
  'Mixing Engineer',
  'Software Engineer',
  'Truck Costumer',
  'Color Assistant',
  'Title Designer',
  'Camera Operator',
  'Assistant Camera',
  'First Assistant Camera',
  'Additional First Assistant Camera',
  'Second Assistant Camera',
  'Additional Second Assistant Camera',
  '"A" Camera Operator',
  'First Assistant "A" Camera',
  'Second Assistant "A" Camera',
  'Third Assistant "A" Camera',
  '"B" Camera Operator',
  'First Assistant "B" Camera',
  'Second Assistant "B" Camera',
  'Third Assistant "B" Camera',
  '"C" Camera Operator',
  'First Assistant "C" Camera',
  'Second Assistant "C" Camera',
  'Third Assistant "C" Camera',
  '"D" Camera Operator',
  'First Assistant "D" Camera',
  'Second Assistant "D" Camera',
  'Third Assistant "D" Camera',
  'Aerial Camera',
  'Aerial Camera Technician',
  'Camera Technician',
  'Helicopter Camera',
  'Additional Camera',
  'Second Unit Director of Photography',
  'Art Department Coordinator',
  'Graphic Designer',
  'First Assistant Sound Editor',
  'Assistant Sound Editor',
  'Sound Effects Editor',
  'Sound Effects Designer',
  'Scoring Mixer',
  'Additional Editing',
  'Set Decorating Coordinator',
  'Book',
  'Associate Producer',
  'Makeup Department Head',
  'Prosthetic Supervisor',
  'Prosthetics',
  'Prosthetic Makeup Artist',
  'Prosthetic Designer',
  'Prosthetics Sculptor',
  'Animatronic and Prosthetic Effects',
  'Scenic Artist',
  'Leadman',
  'Greensman',
  'Supervising ADR Editor',
  'ADR Supervisor',
  'ADR Coordinator',
  'ADR & Dubbing',
  'ADR Editor',
  'ADR Mixer',
  'ADR Engineer',
  'ADR Recordist',
  'ADR Voice Casting',
  'Construction Coordinator',
  'Wigmaker',
  'Tattoo Designer',
  'Camera Department Production Assistant',
  'Shop Electric',
  'Key Construction Grip',
  'Additional Soundtrack',
  'Post Production Supervisor',
  'Supervising Art Director',
  'Co-Art Director',
  'Second Assistant Art Director',
  'Standby Art Director',
  'Assistant Art Director',
  'Visual Effects Art Director',
  'Utility Stunts',
  'Second Unit First Assistant Director',
  'Conceptual Illustrator',
  'Driver',
  'Costume Designer',
  'Digital Imaging Technician',
  'Wardrobe Master',
  'Wardrobe Supervisor',
  'Wardrobe Coordinator',
  'Wardrobe Assistant',
  'Additional Wardrobe Assistant',
  'Additional Sound Re-Recording Mixer',
  'Costume Coordinator',
  'Assistant Costume Designer',
  'Digital Intermediate',
  'Executive Music Producer',
  'Original Music Composer',
  'Music Director',
  'Music Supervisor',
  'Music Arranger',
  'Music Producer',
  'Music Consultant',
  'Music Coordinator',
  'Music Score Producer',
  'Music Programmer',
  'Musician',
  'Additional Music',
  'Music',
  'Supervising Music Editor',
  'Music Editor',
  'Temp Music Editor',
  'Dailies Technician',
  'Dailies Manager',
  'Dailies Operator',
  'Clapper Loader',
  'Transportation Captain',
  'Transportation Co-Captain',
  'Transportation Coordinator',
  'Supervising Dialogue Editor',
  'Production Accountant',
  'First Assistant Accountant',
  'Post Production Accountant',
  'Second Assistant Accountant',
  'Payroll Accountant',
  'Assistant Accountant',
  'Post Coordinator',
  'Digital Effects Supervisor',
  'Best Boy Grip',
  'In Memory Of',
  '3D Supervisor',
  'Animal Coordinator',
  'Production Runner',
  'Dialogue Editor',
  'Utility Sound',
  'Stunt Double',
  'Dialect Coach',
  'Dialogue Coach',
  'Rigging Grip',
  'Rigging Gaffer',
  'Electrician',
  'Lighting Director',
  'Lighting Supervisor',
  'Chief Lighting Technician',
  'Assistant Chief Lighting Technician',
  'Lighting Technician',
  'Lighting Programmer',
  'Lighting Design',
  'Lighting Artist',
  'Additional Lighting Technician',
  'Set Production Assistant',
  'Set Medic',
  'Unit Publicist',
  'Visual Effects Production Assistant',
  'Main Title Designer',
  'Sculptor',
  'Color Timer',
  'Storyboard Artist',
  'First Assistant Editor',
  'Assistant Sound Engineer',
  'Pilot',
  'Compositor',
  'Aerial Coordinator',
  'Sound Recordist',
  'Supervising Armorer',
  'Armorer',
  'Production Secretary',
  'First Assistant Makeup Artist',
  'Ager/Dyer',
  'Standby Painter',
  'Costume Standby',
  'Costume Assistant',
  'Author',
  'First Assistant Art Direction',
  'Sound Mix Technician',
  'Textile Artist',
  'Costumer',
  'Construction Foreman',
  'Concept Artist',
  'Orchestrator',
  'Props',
  'Underwater Director of Photography',
  'Underwater Camera',
  'Underwater Gaffer',
  'Sequence Supervisor',
  'Supervising Producer',
  'Coordinating Producer',
  'Lead Painter',
  'Security Coordinator',
  'Rotoscoping Artist',
  'Pre-Visualization Supervisor',
  'Digital Color Timer',
  'Visual Effects Technical Director',
  'Stereoscopic Supervisor',
  'Stereoscopic Editor',
  'Animation Technical Director',
  'CG Animator',
  'Creature Technical Director',
  'Additional Director of Photography',
  'VFX Lighting Artist',
  'Art Department Manager',
  'Supervising Film Editor',
  'Lighting Camera',
  'Lead Character Designer',
  'Supervising Animator',
  'Ultimate Arm Operator',
  '3D Editor',
  'Location Sound Mixer',
  'Consulting Editor',
  'Dressing Prop',
  'Art Department Assistant',
  'Focus Puller',
  'Construction Manager',
  'Marine Coordinator',
  'Assistant Production Manager',
  'Unit Manager',
  'Post Production Assistant',
  'Projection',
  'Propmaker',
  'Quality Control Supervisor',
  'Apprentice Sound Editor',
  'Head Greensman',
  'Art Department Production Assistant',
  'Digital Supervisor',
  'Pre-Visualization Coordinator',
  'Technical Advisor',
  'Executive In Charge Of Post Production',
  'Assistant Unit Manager',
  'Sound Assistant',
  'Special Effects Manager',
  'Drone Pilot',
  'Drone Operator',
  'Drone Cinematographer',
  'First Company Grip',
  'Executive Visual Effects Producer',
  'Digital Effects Producer',
  'Makeup Effects',
  'Visual Effects Camera',
  'Dolby Consultant',
  'Best Boy Electric',
  'Key Rigging Grip',
  'Generator Operator',
  'Tailor',
  'Visual Effects Designer',
  'Loader',
  'Additional Editor',
  'Post Production Coordinator',
  'Digital Compositor',
  'Location Coordinator',
  'Location Manager',
  'Location Assistant',
  'Additional Production Assistant',
  'Editorial Production Assistant',
  'Assistant Location Manager',
  'Location Production Assistant',
  'Location Scout',
  'Studio Teacher',
  'Production Controller',
  'Production Driver',
  'Additional Grip',
  'Key Set Production Assistant',
  'Visual Effects Production Manager',
  'Executive In Charge Of Production',
  'Contact Lens Technician',
  'Contact Lens Designer',
  'Painter',
  'Motion Capture Artist',
  'Conceptual Design',
  'Legal Services',
  'Animation',
  'Animation Director',
  'Senior Modeller',
  'Craft Service',
  'Camera Production Assistant',
  '24 Frame Playback',
  'Editorial Staff',
  'Set Dressing Artist',
  'Finance',
  'Production Office Assistant',
  'Character Designer',
  'Supervising Animation Director',
  'Original Story',
  'Prop Designer',
  '3D Director',
  '3D Animator',
  'Background Designer',
  'Sound Director',
  'Sound Effects',
  'Wig Designer',
  'Conductor',
  'Sound Engineer',
  'Color Designer',
  'Theme Song Performance',
  'Key Animation',
  'Techno Crane Operator',
  'BTS Photographer',
  'Camera Loader',
  'Epk Camera Operator',
  'Russian Arm Operator',
  'Digital Intermediate Assistant',
  'Publicist',
  'Travel Coordinator',
  'Comic Book',
  'Lyricist',
  'Theatre Play',
  'Administration',
  'Modelling Supervisor',
  'Layout Supervisor',
  '3D Generalist',
  'Vocals',
  'Story Consultant',
  'Pyrotechnic Supervisor',
  'Steadycam',
  'CGI Director',
  'Characters',
  'Production Designer',
  'Key Grip Production Assistant',
  'Additional Key Grip',
  'Animal Wrangler',
  'Clearances Coordinator',
  'Script',
  'Special Effects Key Makeup Artist',
  'Cableman',
  'Production Office Coordinator',
  'Creature Design',
  'Translator',
  'Consulting Producer',
  'Playback Singer',
  'Dialogue',
  'Second Assistant Sound',
  '3D Artist',
  'Accounting Clerk Assistant',
  'Camera Car',
  'Assistant Director Trainee',
  'Continuity',
  'Senior Visual Effects Supervisor',
  'Post Producer',
  'Additional Photography',
  'Technical Supervisor',
  'Senior Animator',
  'Generalist',
  'Matchmove Supervisor',
  'Security',
  'Storyboard',
  'Production Illustrator',
  'Systems Administrators & Support',
  'Digital Compositors',
  'VFX Director of Photography',
  'Visual Effects Assistant Editor',
  'Special Effects Assistant',
  'Effects Supervisor',
  'Assistant Craft Service',
  'Lead Animator',
  'Score Engineer',
  'Chef',
  'Assistant Chef',
  'Studio Teachers',
  'Swing',
  'Director of Operations',
  'Executive Assistant',
  'Intern',
  'Camera Intern',
  'Property Builder',
  'Set Propsman',
  'Accountant',
  'Executive Consultant',
  'Storyboard Designer',
  'Transcriptions',
  'Script Consultant',
  'Project Manager',
  'Musical',
  'Best Boy Electrician',
  'Manager of Operations',
  'General Manager',
  'Special Sound Effects',
  'Film Processor',
  'Imaging Science',
  'Editorial Services',
  'Post-Production Manager',
  'Additional Set Photographer',
  'Epk Producer',
  'Special Props',
  'Daily Electrics',
  'Costume Illustrator',
  'Roto Supervisor',
  'Visual Effects Director',
  'Sequence Lead',
  'Military Consultant',
  'Art Direction Intern',
  'Lead Set Dresser',
  'Additional Writing',
  'Production Director',
  'Controller',
  'Second Assistant Director Trainee',
  'Head of Story',
  'Digital Producer',
  'Supervising Technical Director',
  'Story Supervisor',
  'Camera Supervisor',
  'Layout',
  'Adaptation',
  'Presenter',
  'Machinist',
  'Idea',
  'Assistant Production Design',
  'Story Artist',
  'Story Coordinator',
  'Editorial Coordinator',
  'Lighting Coordinator',
  'Finishing Producer',
  'Original Concept',
  'Supervising Sound Effects Editor',
  'Animatronics Designer',
  'Animatronics Supervisor',
  '2D Supervisor',
  'Construction Grip',
  'Video Game',
  'Set Painter',
  'Recording Supervision',
  'Second Company Grip',
  'Background Casting Director',
  'Art Designer',
  'Costume Set Supervisor',
  'Paint Coordinator',
  'Stage Director',
  'Charge Scenic Artist',
  '3D Modeller',
  'Archival Footage Research',
  'Stereoscopic Coordinator',
  'Lighting Manager',
  'Pipeline Technical Director',
  'Vehicles Wrangler',
  'Co-Editor',
  'Additional Still Photographer',
  'Extras Dresser',
  'Information Systems Manager',
  'Creature Effects Technical Director',
  'Head of Layout',
  'Simulation & Effects Artist',
  'Contact Lens Painter',
  'Senior Generalist',
  'Animation Department Coordinator',
  'Executive in Charge of Finance',
  'Decorator',
  'Main Title Theme Composer',
  'Story Editor',
  'Digital Conform Editor',
  'Genetator Operator',
  'Standby Rigger',
  'Set Dressing Production Assistant',
  'Stunts Coordinator',
  'Health and Safety',
  'Post Production Consulting',
  'Floor Runner',
  'Picture Car Coordinator',
  'Stand In',
  'Other',
  'Thanks',
];

export default roles;